### ISSUE TITLE
error while running make update-api 

### ISSUE THREAD

**Issue by ganeshi4u** [nitrogen-project/android_frameworks_base#35]
FAILED: /bin/bash /home/techkid/nos/out/target/common/docs/doc-comment-check-timestamp.rsp
frameworks/base/core/java/android/widget/SeekBar.java:41: error 101: Unresolved link/see tag "ProgressBar#setMax(int)" in android.preference.CustomSeekBarPreference
DroidDoc took 132 sec. to write docs to /home/techkid/nos/out/target/common/docs/doc-comment-check
ninja: build stopped: subcommand failed.
build/core/ninja.mk:148: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1

**Comment by xyyx** [comment]
Check your sources. Doesn't have it. I make builds for many devices every day

**Comment by ganeshi4u** [comment]
Hi i have resynced the whole source again but still the same error persists? :( I have read in a couple of forums that this might be an issue of jdk, i'm using openjdk version "1.8.0_121". Could you tell me which one are you using? I never had issues compiling AOSP roms with my device tree before.
I'm trying to build it on ubuntu 16.04 if that could be a issue.
